### ISSUE TITLE
Fork와 Branch의 차이가 뭔가요??

### ISSUE THREAD

**Issue by manggny** [StudyGroupPKU/TESTs#31]
fork는 원본을 복사해서 자신의 저장소에 저장한 후에 고치고 pull request로 병합 신청을 하는데,
branch도 원본을 복사해 가져와서 수정후에 master 브랜치에 병합신청해서 merge한다고 하던데요..
혹시 목적이나 용도상의 명확한 구분이 있나요?? 각각의 fork도 또 여러가지 브랜치를 가질수 있더라구요 !
감사합니다!

**Comment by junholeephy** [comment]
일단 매우 좋은 질문! 
우선, 이건 조금더 복잡하고, 우리가 현재 사용하진 않을꺼라, 관심 있는 분만 읽어 보시길 추천해요.

조그만 지적으로 먼저 시작하자면, "fork"는 동사, "branch"는 명사.
"fork"를 한다는 의미는, 다른 사람의 repository(upstream/origin)를 자기 자신의 repository(origin)로 가져 온다는 의미를 가져.
 One repository(repo) may contain multiple branches. For our case, you can check this on "statistics" repository, which contains "master" and "junho" branch. 
Once one create a repo(not by "fork"), it only has "master" branch, but the owner of the repo able to create multiple branches, in order to have multiple version of codes.
But, the alternative branches can be merged to master's in order to make them even. ("merge" does not mean disappear of the branch)
And, if other user "fork"s the multiple branches contained repo, he is "fork"ing all of the branches to his repo

**Comment by junholeephy** [comment]
내 답변이 도움이 됬을지 모르겠네. 읽어보고 궁금한게 있으면 추가 질문 부탁!

**Comment by manggny** [comment]
ㅎㅎ 감사합니다!! 잘 이해 됏어요!!
